[agent]
  interval = "2s"
  flush_interval = "2s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics   = ["sensors/post/+/metrics"]
  data_format = "json"
  tag_keys    = ["post_id"]
  name_override = "power_metrics"

[[outputs.influxdb_v2]]
  urls         = ["http://influxdb:8086"]
  token        = "my-super-secret-token"
  organization = "ase"
  bucket       = "sensors"
